# Generated by Django 4.2.5 on 2023-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/defaultava.jpg', upload_to='profile_photos'),
        ),
    ]
