# Generated by Django 4.2.5 on 2023-09-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_films_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='link_to_watch',
            field=models.TextField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='films',
            name='planned_to_watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='films',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
